#pragma once

enum Key: unsigned char {
    NONE = 0x00, FN,

    A = 0x04, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    N1, N2, N3, N4, N5, N6, N7, N8, N9, N0,
    ENTER, ESC, BACKSPACE, TAB, SPACE,
    MINUS, EQUAL, LEFTBRACE, RIGHTBRACE, BACKSLASH,
    SEMICOLON = 0x33, APOSTROPHE, GRAVE, COMMA, PERIOD, SLASH,
    CAPSLOCK, 
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    PRINT, SCROLLLOCK, PAUSE, INSERT, HOME, PAGEUP, DELETE, END, PAGEDOWN,
    RIGHT, LEFT, DOWN, UP,

    NUMLOCK, KPSLASH, KPASTERISK, KPMINUS, KPPLUS, KPENTER,
    KP1, KP2, KP3, KP4, KP5, KP6, KP7, KP8, KP9, KP0, KPDOT,

    APPLICATION = 0x65, POWER, KPEQUAL,
    F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,
    EXECUTE, HELP, MENU, SELECT, STOP, REDO, UNDO, CUT, COPY, PASTE, FIND,
    MUTE, VOLUMEUP, VOLUMEDOWN, 

    LCTRL = 0xE0, LSHIFT, LALT, LGUI,
    RCTRL, RSHIFT, RALT, RGUI
};
